version: "3.7"
services:
  db:
    build:
      context: ./toppel-db
      dockerfile: Dockerfile
  web:
    build:
      context: ./toppel-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"
