version: "3.7"
services:
  db:
    build:
      context: ./toppel-db
      dockerfile: Dockerfile
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  web:
    build:
      context: ./toppel-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    volumes:
      - ./toppel-web/toppel:/app:rw
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
